# Generated by Django 2.2.6 on 2019-12-12 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theloai',
            options={'ordering': ('ten',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
