# Generated by Django 2.2.6 on 2019-12-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tin', '0002_auto_20191212_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theloai',
            options={},
        ),
        migrations.AlterField(
            model_name='loaitin',
            name='tenKhongDau',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='theloai',
            name='ten',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='theloai',
            name='tenKhongDau',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='tin',
            name='tieuDe',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tin',
            name='tieuDeKhongDau',
            field=models.SlugField(unique=True),
        ),
    ]
