# Generated by Django 2.2.6 on 2019-12-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tin', '0003_auto_20191212_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaitin',
            name='tenKhongDau',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='theloai',
            name='tenKhongDau',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tin',
            name='anh',
            field=models.ImageField(upload_to='images/%y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tin',
            name='tieuDeKhongDau',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
